version: '{build}'
skip_tags: true
image: Visual Studio 2019
configuration: Release
platform: x86
build:
  project: compressors\tilecompressordlls.sln
  parallel: true
  verbosity: minimal
after_build:
- cmd: >-
    7z a bmp2tilecompressors.zip %APPVEYOR_BUILD_FOLDER%\compressors\Release\*.dll

    7z a bmp2tiledecompressors.zip %APPVEYOR_BUILD_FOLDER%\decompressors\*.asm
artifacts:
- path: '*.zip'
deploy:
- provider: GitHub
  release: Build ${appveyor_build_number}
  auth_token:
    secure: KbY6wD6RTuotJxi7BdGQWg4e6rEc9OMP1u0keEYIrO9CrV9C8OJNSTjaOAmNH1LJ
  force_update: true